[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99
skip = ["docs/"]
src_paths = ["src", "tests"]
